# Generated by Django 3.2.5 on 2021-10-07 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 54, 55, 900990, tzinfo=utc)),
        ),
    ]
