# Generated by Django 3.2.5 on 2021-10-07 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0003_alter_airport_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 16, 22, 39, 488723, tzinfo=utc)),
        ),
    ]
