# Generated by Django 3.2.6 on 2022-02-20 05:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0004_alter_airport_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='black', max_length=50)),
                ('fill_color', models.CharField(default='orange', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 5, 20, 24, 329011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='obstruction',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='obstruction',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='obstruction',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='obstruction',
            name='site_elevation',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noc.area')),
            ],
        ),
    ]
