# Generated by Django 3.2.6 on 2022-02-22 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0006_auto_20220220_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='reference',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 17, 29, 44, 949071, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='area',
            name='area_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noc.areatype'),
            preserve_default=False,
        ),
    ]
