# Generated by Django 3.2.6 on 2022-02-23 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0010_auto_20220223_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 16, 24, 40, 902503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noc.route'),
        ),
    ]
