# Generated by Django 3.2.6 on 2022-02-23 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0011_auto_20220223_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='AtsRoute',
        ),
        migrations.RenameField(
            model_name='waypoint',
            old_name='route',
            new_name='ats_route',
        ),
        migrations.AlterField(
            model_name='airport',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 16, 55, 5, 3260, tzinfo=utc)),
        ),
    ]
