# Generated by Django 3.2.6 on 2022-02-23 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0012_auto_20220223_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 17, 3, 55, 724558, tzinfo=utc)),
        ),
    ]
